// src/lib/LanguageContext.jsx
import React, { createContext, useContext, useState } from "react";

const translations = {
  es: {
    // ── NAVEGACIÓN
    nav_general:"General", nav_registros:"Registros", nav_rrhh:"RRHH",
    nav_jornada:"Mi jornada", nav_cuenta:"Cuenta", nav_inicio:"Inicio",
    nav_empresas:"Empresas", nav_empleados:"Empleados", nav_fichajes:"Fichajes",
    nav_incidencias:"Incidencias", nav_informe_pdf:"Informe PDF",
    nav_vacaciones:"Vacaciones", nav_enfermedad:"Enfermedad", nav_nominas:"Nóminas",
    nav_fichar:"Fichar", nav_historial:"Mi historial", nav_password:"Contraseña",
    nav_cerrar_sesion:"Cerrar sesión",
    // ── GENERAL
    cargando:"Cargando...", guardando:"Guardando...", guardar:"Guardar",
    cancelar:"Cancelar", eliminar:"Eliminar", editar:"✏ Editar", ver:"Ver",
    // ── LOGIN
    login_email:"Correo electrónico", login_password:"Contraseña",
    login_btn:"Iniciar sesión", login_cargando:"Entrando...",
    login_error:"Email o contraseña incorrectos. Inténtalo de nuevo.",
    login_ayuda:"¿Problemas para acceder? Contacta con tu administrador.",
    login_subtitulo:"Sistema de registro de jornada · RDL 8/2019",
    // ── DASHBOARD
    dash_bienvenido:"Bienvenido", dash_empresas:"Empresas S.L.",
    dash_empresas_sub:"registradas", dash_empleados:"Empleados",
    dash_empleados_sub:"activos", dash_fichajes_hoy:"Fichajes hoy",
    dash_fichajes_hoy_sub:"registros de hoy", dash_estado:"Estado",
    dash_estado_sub:"Sistema activo", dash_ultimos:"Últimos fichajes de hoy",
    dash_actualizar:"↺ Actualizar", dash_empleado:"Empleado",
    dash_empresa:"Empresa", dash_tipo:"Tipo", dash_hora:"Hora",
    dash_sin_fichajes:"Sin fichajes hoy todavía",
    dash_entrada:"⬇ Entrada", dash_salida:"⬆ Salida",
    // ── FICHAR
    fichar_sin_empresa:"Sin empresa", fichar_registros_hoy:"REGISTROS DE HOY",
    fichar_sin_registros:"Sin registros aún hoy",
    fichar_tiempo_hoy:"⏱ Tiempo trabajado hoy:",
    fichar_total_hoy:"✓ Total hoy:",
    fichar_btn_entrada:"⬇ Registrar ENTRADA",
    fichar_btn_salida:"⬆ Registrar SALIDA",
    fichar_registrando:"Registrando...",
    fichar_mi_cuenta:"👤 Mi cuenta ▾",
    fichar_mi_historial:"Mi historial", fichar_mis_incidencias:"Mis incidencias",
    fichar_vacaciones:"Vacaciones", fichar_enfermedad:"Enfermedad",
    fichar_mis_nominas:"Mis nóminas", fichar_cambiar_pwd:"Cambiar contraseña",
    fichar_cerrar_sesion:"Cerrar sesión",
    fichar_confirmar_logout:"¿Seguro? Pulsa de nuevo",
    fichar_error:"Error al registrar. Inténtalo de nuevo.",
    // ── FICHAJES ADMIN
    fichajes_titulo:"Registro de fichajes", fichajes_exportar:"⬇ Exportar Excel",
    fichajes_mes:"Mes", fichajes_empresa:"Empresa",
    fichajes_todas_emp:"Todas las empresas", fichajes_dias:"días registrados",
    fichajes_empleado:"Empleado", fichajes_fecha:"Fecha",
    fichajes_entrada:"Entrada", fichajes_salida:"Salida",
    fichajes_total:"Total horas", fichajes_incidencias:"Incidencias",
    fichajes_sin_datos:"No hay fichajes en este período",
    fichajes_en_curso:"En curso",
    // ── EMPLEADOS
    emp_titulo:"Empleados", emp_nuevo:"+ Nuevo empleado",
    emp_todas_empresas:"Todas las empresas",
    emp_nombre:"Nombre", emp_email:"Email", emp_empresa:"Empresa",
    emp_categoria:"Categoría", emp_rol:"Rol", emp_acciones:"Acciones",
    emp_sin_empleados:"No hay empleados. Añade el primero.",
    emp_modal_nuevo:"Nuevo empleado", emp_modal_editar:"Editar empleado",
    emp_nombre_label:"Nombre completo *", emp_email_label:"Email *",
    emp_pwd_label:"Contraseña inicial *",
    emp_pwd_hint:"El empleado podrá cambiarla después.",
    emp_empresa_label:"Empresa *", emp_empresa_sel:"Selecciona empresa...",
    emp_cat_label:"Categoría profesional", emp_jornada_label:"Tipo de jornada",
    emp_jornada_completa:"Completa (40h)", emp_jornada_parcial:"Parcial",
    emp_rol_label:"Rol en el sistema",
    emp_rol_empleado:"Empleado (solo ficha)",
    emp_rol_rrhh:"RRHH (ve su empresa)",
    emp_rol_admin:"Administrador (acceso total)",
    emp_creando:"Creando empleado...", emp_guardar:"Guardar",
    // ── EMPRESAS
    emp2_titulo:"Empresas S.L.", emp2_nueva:"+ Nueva empresa",
    emp2_col_nombre:"Nombre", emp2_col_cif:"CIF",
    emp2_col_convenio:"Convenio", emp2_col_contacto:"Contacto RRHH",
    emp2_col_acciones:"Acciones",
    emp2_sin:"No hay empresas. Crea la primera.",
    emp2_modal_nueva:"Nueva empresa S.L.", emp2_modal_editar:"Editar empresa",
    emp2_f_nombre:"Nombre completo *", emp2_f_cif:"CIF *",
    emp2_f_domicilio:"Domicilio social", emp2_f_convenio:"Convenio colectivo",
    emp2_f_contacto:"Email responsable RRHH", emp2_guardar:"Guardar empresa",
    // ── INCIDENCIAS
    inc_titulo:"Incidencias", inc_nueva:"+ Nueva incidencia",
    inc_pendiente_txt:"pendiente", inc_pendientes_txt:"pendientes",
    inc_sin_datos:"No hay incidencias",
    inc_opt_todos:"Todos", inc_opt_pendiente:"Pendientes",
    inc_opt_aprobada:"Aprobadas", inc_opt_rechazada:"Rechazadas",
    inc_estado_pendiente:"Pendiente", inc_estado_aprobada:"Aprobada",
    inc_estado_rechazada:"Rechazada",
    inc_modal_nueva:"Nueva incidencia", inc_modal_editar:"Editar incidencia",
    inc_empleado:"Empleado", inc_empleado_sel:"Selecciona empleado...",
    inc_fecha:"Fecha *", inc_hora_correcta:"Hora correcta",
    inc_tipo:"Tipo *", inc_descripcion:"Descripción / Justificación",
    inc_desc_ph:"Explica brevemente el motivo...",
    inc_estado:"Estado", inc_registrada_por:"Registrada por:",
    inc_guardar:"Guardar incidencia",
    // ── VACACIONES
    vac_titulo:"Vacaciones",
    vac_pendiente_txt:"pendiente", vac_pendientes_txt:"pendientes",
    vac_opt_todos:"Todos", vac_opt_pendiente:"Pendientes",
    vac_opt_aprobada:"Aprobadas", vac_opt_rechazada:"Rechazadas",
    vac_solicitar:"+ Solicitar", vac_sin_datos:"No hay solicitudes",
    vac_estado_pendiente:"Pendiente", vac_estado_aprobada:"Aprobada",
    vac_estado_rechazada:"Rechazada",
    vac_modal_nueva:"Nueva solicitud de vacaciones",
    vac_modal_editar:"Editar solicitud",
    vac_empleado:"Empleado", vac_empleado_sel:"Selecciona empleado...",
    vac_fecha_inicio:"Fecha inicio *", vac_fecha_fin:"Fecha fin *",
    vac_dias_naturales:"días naturales",
    vac_motivo:"Motivo (opcional)", vac_motivo_ph:"Vacaciones de verano...",
    vac_estado:"Estado", vac_enviar:"Enviar solicitud", vac_guardando:"Guardando...",
    // ── ENFERMEDAD
    enf_titulo:"Enfermedad y ausencias", enf_por_revisar:"por revisar",
    enf_reportar:"+ Reportar ausencia", enf_sin_datos:"Sin registros",
    enf_estado_reportada:"Reportada", enf_estado_confirmada:"Confirmada",
    enf_estado_resuelta:"Resuelta",
    enf_modal_nueva:"Reportar ausencia", enf_modal_editar:"Editar ausencia",
    enf_empleado:"Empleado", enf_empleado_sel:"Selecciona empleado...",
    enf_tipo:"Tipo *", enf_fecha_inicio:"Fecha inicio *", enf_fecha_fin:"Fecha fin",
    enf_descripcion:"Descripción", enf_desc_ph:"Detalles adicionales...",
    enf_estado:"Estado",
    enf_info:"ℹ Durante ausencia confirmada no es necesario fichar.",
    enf_confirmar:"Confirmar", enf_resolver:"Resolver",
    enf_guardar:"Guardar", enf_guardando:"Guardando...",
    // ── NÓMINAS
    nom_titulo_admin:"Gestión de nóminas", nom_titulo_emp:"Mis nóminas",
    nom_subir:"+ Subir nómina", nom_empresa:"Empresa",
    nom_todas_emp:"Todas las empresas", nom_empleado:"Empleado",
    nom_todos_emp:"Todos los empleados", nom_count:"nóminas",
    nom_sin_datos:"No hay nóminas",
    nom_vacia_titulo:"Aún no tienes nóminas disponibles",
    nom_vacia_sub:"Tu empresa las publicará aquí cuando estén listas",
    nom_descargar:"⬇ Descargar",
    nom_col_mes:"Mes", nom_col_anyo:"Año", nom_col_desc:"Descripción",
    nom_col_acciones:"Acciones", nom_ver:"⬇ Ver",
    nom_modal_titulo:"Subir nómina",
    nom_empresa_label:"Empresa *", nom_empresa_sel:"Selecciona empresa...",
    nom_empleado_label:"Empleado *", nom_empleado_sel:"Selecciona empleado...",
    nom_empleado_primero:"Primero selecciona empresa",
    nom_mes_label:"Mes *", nom_mes_sel:"Selecciona mes...",
    nom_anyo_label:"Año *",
    nom_link_label:"Link de Google Drive *",
    nom_link_hint:"Drive → clic derecho en el PDF → Compartir → \"Cualquier persona con el enlace\" → Copiar enlace",
    nom_desc_label:"Descripción (opcional)",
    nom_desc_ph:"Ej: Nómina ordinaria, con bonus...",
    nom_aviso:"✓ El empleado recibirá una notificación automática al guardar.",
    nom_guardar:"Guardar y notificar", nom_guardando:"Guardando...",
    // ── MI HISTORIAL
    hist_titulo:"Mi historial", hist_descargar:"🖨 Descargar PDF",
    hist_dias_trabajados:"Días trabajados", hist_total_horas:"Total horas mes",
    hist_incidencias:"Incidencias", hist_fecha:"Fecha",
    hist_entrada:"Entrada", hist_salida:"Salida", hist_total:"Total",
    hist_sin_datos:"Sin registros este mes", hist_en_curso:"En curso",
    // ── CAMBIAR CONTRASEÑA
    pwd_titulo:"Cambiar contraseña", pwd_actual:"Contraseña actual",
    pwd_nueva:"Nueva contraseña", pwd_repetir:"Repetir nueva contraseña",
    pwd_btn:"Cambiar contraseña", pwd_guardando:"Guardando...",
    pwd_aviso:"⚠ Tras cambiar la contraseña tendrás que volver a iniciar sesión en todos tus dispositivos.",
    pwd_ph_actual:"Tu contraseña actual",
    pwd_ph_nueva:"Mínimo 6 caracteres",
    pwd_ph_repetir:"Repite la nueva contraseña",
  },

  en: {
    // ── NAVIGATION
    nav_general:"General", nav_registros:"Records", nav_rrhh:"HR",
    nav_jornada:"My Shift", nav_cuenta:"Account", nav_inicio:"Home",
    nav_empresas:"Companies", nav_empleados:"Employees", nav_fichajes:"Time Logs",
    nav_incidencias:"Incidents", nav_informe_pdf:"PDF Report",
    nav_vacaciones:"Holidays", nav_enfermedad:"Sick Leave", nav_nominas:"Payslips",
    nav_fichar:"Clock In/Out", nav_historial:"My History", nav_password:"Password",
    nav_cerrar_sesion:"Log out",
    // ── GENERAL
    cargando:"Loading...", guardando:"Saving...", guardar:"Save",
    cancelar:"Cancel", eliminar:"Delete", editar:"✏ Edit", ver:"View",
    // ── LOGIN
    login_email:"Email address", login_password:"Password",
    login_btn:"Sign in", login_cargando:"Signing in...",
    login_error:"Incorrect email or password. Please try again.",
    login_ayuda:"Having trouble? Contact your administrator.",
    login_subtitulo:"Working hours register · RDL 8/2019",
    // ── DASHBOARD
    dash_bienvenido:"Welcome", dash_empresas:"Companies",
    dash_empresas_sub:"registered", dash_empleados:"Employees",
    dash_empleados_sub:"active", dash_fichajes_hoy:"Clock-ins today",
    dash_fichajes_hoy_sub:"today's records", dash_estado:"Status",
    dash_estado_sub:"System active", dash_ultimos:"Latest clock-ins today",
    dash_actualizar:"↺ Refresh", dash_empleado:"Employee",
    dash_empresa:"Company", dash_tipo:"Type", dash_hora:"Time",
    dash_sin_fichajes:"No clock-ins yet today",
    dash_entrada:"⬇ Clock in", dash_salida:"⬆ Clock out",
    // ── FICHAR
    fichar_sin_empresa:"No company", fichar_registros_hoy:"TODAY'S RECORDS",
    fichar_sin_registros:"No records yet today",
    fichar_tiempo_hoy:"⏱ Time worked today:",
    fichar_total_hoy:"✓ Total today:",
    fichar_btn_entrada:"⬇ CLOCK IN",
    fichar_btn_salida:"⬆ CLOCK OUT",
    fichar_registrando:"Recording...",
    fichar_mi_cuenta:"👤 My account ▾",
    fichar_mi_historial:"My history", fichar_mis_incidencias:"My incidents",
    fichar_vacaciones:"Holidays", fichar_enfermedad:"Sick leave",
    fichar_mis_nominas:"My payslips", fichar_cambiar_pwd:"Change password",
    fichar_cerrar_sesion:"Log out",
    fichar_confirmar_logout:"Sure? Press again",
    fichar_error:"Error recording. Please try again.",
    // ── FICHAJES ADMIN
    fichajes_titulo:"Time log records", fichajes_exportar:"⬇ Export Excel",
    fichajes_mes:"Month", fichajes_empresa:"Company",
    fichajes_todas_emp:"All companies", fichajes_dias:"days recorded",
    fichajes_empleado:"Employee", fichajes_fecha:"Date",
    fichajes_entrada:"Clock in", fichajes_salida:"Clock out",
    fichajes_total:"Total hours", fichajes_incidencias:"Incidents",
    fichajes_sin_datos:"No records for this period",
    fichajes_en_curso:"In progress",
    // ── EMPLEADOS
    emp_titulo:"Employees", emp_nuevo:"+ New employee",
    emp_todas_empresas:"All companies",
    emp_nombre:"Name", emp_email:"Email", emp_empresa:"Company",
    emp_categoria:"Category", emp_rol:"Role", emp_acciones:"Actions",
    emp_sin_empleados:"No employees. Add the first one.",
    emp_modal_nuevo:"New employee", emp_modal_editar:"Edit employee",
    emp_nombre_label:"Full name *", emp_email_label:"Email *",
    emp_pwd_label:"Initial password *",
    emp_pwd_hint:"The employee can change it later.",
    emp_empresa_label:"Company *", emp_empresa_sel:"Select company...",
    emp_cat_label:"Job category", emp_jornada_label:"Shift type",
    emp_jornada_completa:"Full time (40h)", emp_jornada_parcial:"Part time",
    emp_rol_label:"System role",
    emp_rol_empleado:"Employee (clock only)",
    emp_rol_rrhh:"HR (company view)",
    emp_rol_admin:"Administrator (full access)",
    emp_creando:"Creating employee...", emp_guardar:"Save",
    // ── EMPRESAS
    emp2_titulo:"Companies", emp2_nueva:"+ New company",
    emp2_col_nombre:"Name", emp2_col_cif:"Tax ID",
    emp2_col_convenio:"Agreement", emp2_col_contacto:"HR Contact",
    emp2_col_acciones:"Actions",
    emp2_sin:"No companies. Create the first one.",
    emp2_modal_nueva:"New company", emp2_modal_editar:"Edit company",
    emp2_f_nombre:"Full name *", emp2_f_cif:"Tax ID *",
    emp2_f_domicilio:"Registered address", emp2_f_convenio:"Collective agreement",
    emp2_f_contacto:"HR manager email", emp2_guardar:"Save company",
    // ── INCIDENCIAS
    inc_titulo:"Incidents", inc_nueva:"+ New incident",
    inc_pendiente_txt:"pending", inc_pendientes_txt:"pending",
    inc_sin_datos:"No incidents",
    inc_opt_todos:"All", inc_opt_pendiente:"Pending",
    inc_opt_aprobada:"Approved", inc_opt_rechazada:"Rejected",
    inc_estado_pendiente:"Pending", inc_estado_aprobada:"Approved",
    inc_estado_rechazada:"Rejected",
    inc_modal_nueva:"New incident", inc_modal_editar:"Edit incident",
    inc_empleado:"Employee", inc_empleado_sel:"Select employee...",
    inc_fecha:"Date *", inc_hora_correcta:"Correct time",
    inc_tipo:"Type *", inc_descripcion:"Description / Justification",
    inc_desc_ph:"Briefly explain the reason...",
    inc_estado:"Status", inc_registrada_por:"Registered by:",
    inc_guardar:"Save incident",
    // ── VACACIONES
    vac_titulo:"Holidays",
    vac_pendiente_txt:"pending", vac_pendientes_txt:"pending",
    vac_opt_todos:"All", vac_opt_pendiente:"Pending",
    vac_opt_aprobada:"Approved", vac_opt_rechazada:"Rejected",
    vac_solicitar:"+ Request", vac_sin_datos:"No requests",
    vac_estado_pendiente:"Pending", vac_estado_aprobada:"Approved",
    vac_estado_rechazada:"Rejected",
    vac_modal_nueva:"New holiday request",
    vac_modal_editar:"Edit request",
    vac_empleado:"Employee", vac_empleado_sel:"Select employee...",
    vac_fecha_inicio:"Start date *", vac_fecha_fin:"End date *",
    vac_dias_naturales:"calendar days",
    vac_motivo:"Reason (optional)", vac_motivo_ph:"Summer holidays...",
    vac_estado:"Status", vac_enviar:"Submit request", vac_guardando:"Saving...",
    // ── ENFERMEDAD
    enf_titulo:"Sick leave & absences", enf_por_revisar:"to review",
    enf_reportar:"+ Report absence", enf_sin_datos:"No records",
    enf_estado_reportada:"Reported", enf_estado_confirmada:"Confirmed",
    enf_estado_resuelta:"Resolved",
    enf_modal_nueva:"Report absence", enf_modal_editar:"Edit absence",
    enf_empleado:"Employee", enf_empleado_sel:"Select employee...",
    enf_tipo:"Type *", enf_fecha_inicio:"Start date *", enf_fecha_fin:"End date",
    enf_descripcion:"Description", enf_desc_ph:"Additional details...",
    enf_estado:"Status",
    enf_info:"ℹ No clock-in required during confirmed absence.",
    enf_confirmar:"Confirm", enf_resolver:"Resolve",
    enf_guardar:"Save", enf_guardando:"Saving...",
    // ── NÓMINAS
    nom_titulo_admin:"Payslip management", nom_titulo_emp:"My payslips",
    nom_subir:"+ Upload payslip", nom_empresa:"Company",
    nom_todas_emp:"All companies", nom_empleado:"Employee",
    nom_todos_emp:"All employees", nom_count:"payslips",
    nom_sin_datos:"No payslips",
    nom_vacia_titulo:"No payslips available yet",
    nom_vacia_sub:"Your company will publish them here when ready",
    nom_descargar:"⬇ Download",
    nom_col_mes:"Month", nom_col_anyo:"Year", nom_col_desc:"Description",
    nom_col_acciones:"Actions", nom_ver:"⬇ View",
    nom_modal_titulo:"Upload payslip",
    nom_empresa_label:"Company *", nom_empresa_sel:"Select company...",
    nom_empleado_label:"Employee *", nom_empleado_sel:"Select employee...",
    nom_empleado_primero:"Select company first",
    nom_mes_label:"Month *", nom_mes_sel:"Select month...",
    nom_anyo_label:"Year *",
    nom_link_label:"Google Drive link *",
    nom_link_hint:"Drive → right-click PDF → Share → \"Anyone with the link\" → Copy link",
    nom_desc_label:"Description (optional)",
    nom_desc_ph:"E.g.: Regular payslip, with bonus...",
    nom_aviso:"✓ The employee will receive an automatic notification when saved.",
    nom_guardar:"Save & notify", nom_guardando:"Saving...",
    // ── MI HISTORIAL
    hist_titulo:"My history", hist_descargar:"🖨 Download PDF",
    hist_dias_trabajados:"Days worked", hist_total_horas:"Total hours this month",
    hist_incidencias:"Incidents", hist_fecha:"Date",
    hist_entrada:"Clock in", hist_salida:"Clock out", hist_total:"Total",
    hist_sin_datos:"No records this month", hist_en_curso:"In progress",
    // ── CAMBIAR CONTRASEÑA
    pwd_titulo:"Change password", pwd_actual:"Current password",
    pwd_nueva:"New password", pwd_repetir:"Repeat new password",
    pwd_btn:"Change password", pwd_guardando:"Saving...",
    pwd_aviso:"⚠ After changing your password you will need to sign in again on all your devices.",
    pwd_ph_actual:"Your current password",
    pwd_ph_nueva:"Minimum 6 characters",
    pwd_ph_repetir:"Repeat new password",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("es");
  const t = (key) => translations[lang][key] ?? key;
  const toggleLang = () => setLang((l) => (l === "es" ? "en" : "es"));
  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
